import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Navbar from '../components/Navbar/Navbar';
import styles from '../styles/Home.module.css';

import { createTheme, ThemeProvider } from '@mui/material/styles';

const theme = createTheme({
  palette: {
    primary: {
      main: '#92cfbb',
      light: '#a7d8c8',
    },
    secondary: {
      main: '#4A4A4A',
    },
  },
});

const Home: NextPage = () => {
  return (
    <ThemeProvider theme={theme}>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar title="AINews" />
        <main className={styles.main}></main>

        <footer className={styles.footer}></footer>
      </div>
    </ThemeProvider>
  );
};

export default Home;
